name = "receipt-like-ledger"
compatibility_date = "2026-08-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "receipt_ledger_db"
database_id = "c512fbb0-d637-4e1d-a22c-d15135c65362"

[vars]
DEFAULT_LEDGER_TITLE = "小票记账本 (Receipt Ledger)"
